=== nebgor/Personal-digital-sky-survey/APP/SkyObservations.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2014 aparup

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
              <!-- definition of simple types -->
    <xs:simpleType name="objType">
        <xs:restriction base="xs:NMTOKEN">
            <!--- need some named elements, star,nebula,cluster,galaxy-->
            <xs:enumeration value="STAR"/>
            <xs:enumeration value="NEBULA"/>
            <xs:enumeration value="CLUSTER"/>
            <xs:enumeration value="GALAXY"/>
            <xs:enumeration value="PLANET"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ordType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="ALTAZ"/>
            <xs:enumeration value="EQ"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="SkyObservations">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0"> <!-- Journal ALL the observations -->
                <xs:element name="SkyObservation">
                    <xs:complexType>
                        <xs:all minOccurs="1">
                            <xs:element name="date" type="xs:long"/>
                            <!-- where - useful to plot on a star chart later. -->
                            <xs:element name="coordinate">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element type="xs:string" name="ords"/><!--in defined coordinate system,  @todo need to validate this data-->
                                    </xs:all>
                                    <xs:attribute type="xs:string" name="ordType"/><!--this is not really used yet.-->
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="notes" type="xs:string"/> <!-- maybe blank-->
                            <xs:element name="type" type="objType"/>
                            <xs:element name="hops">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:IDREF" maxOccurs="10" minOccurs="0"/> <!-- hops should be short (keyref) -->
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--<xs:element name="number" type="xs:integer"/>
                            will go deeper into cataloging later -->
                            <xs:element name="extra">
                                <xs:complexType>
                                    <xs:choice maxOccurs="4" minOccurs="0">
                                        <xs:element name="size" type="xs:integer"/>
                                        <xs:element name="appmag" type="xs:integer"/>
                                        <xs:element name="relmag" type="xs:integer"/>
                                        <xs:element name="spectrum" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nebgor/Personal-digital-sky-survey/APP/SkyObs.xml
<?xml version="1.0" encoding="UTF-8"?>
<SkyObservations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SkyObservations.xsd">
    <SkyObservation id="a-1">
        <date>1415292313</date>
        <coordinate ordType="EQ">
            <ords>18.324,20.6564</ords>
        </coordinate>
        <hops/>
        <type>STAR</type>
        <name>vdset</name>
        <notes>first notes56</notes>
        <extra/>
    </SkyObservation>
    <SkyObservation id="a-2">
        <date>1412000735</date>
        <coordinate ordType="EQ">
            <ords>11.324,150.6564</ords>
        </coordinate>
        <hops>
            <id>a-1</id>
        </hops>    
        <type>NEBULA</type>
        <name>basfer</name>
        <notes>test notes</notes>
        <extra>
            <size>3</size>
        </extra>
    </SkyObservation>
    <SkyObservation id="a-3">
        <date>1415292373</date>
        <coordinate ordType="EQ">
            <ords>7.324,90.6564</ords>
        </coordinate>
        <hops>
            <id>a-3</id>
            <id>a-3</id>
        </hops>
        <type>CLUSTER</type>
        <name>casdfs</name>
        <notes>hoola hodf</notes>
        <extra>
            <appmag>-2</appmag>
            <relmag>4</relmag>
        </extra>
    </SkyObservation>
    <SkyObservation id="a-4">
        <date>1415292452</date>
        <coordinate ordType="EQ">
            <ords>20.324,208.6564</ords>
        </coordinate>
        <hops>
            <id>a-4</id>
            <id>a-4</id>
        </hops>
        <type>GALAXY</type>
        <name>aefsa</name>
        <notes>nothing</notes>
        <extra>
            <appmag>-3</appmag>
            <relmag>5</relmag>
        </extra>
    </SkyObservation>
    <SkyObservation id="a-5">
        <date>1415290827</date>
        <coordinate ordType="EQ">
            <ords>3.324,300.6564</ords>
        </coordinate>
        <hops>
            <id>a-1</id>
            <id>a-2</id>
        </hops>
        <type>PLANET</type>
        <name>aasf4w</name>
        <notes>test entries</notes>
        <extra>
            <appmag>-3</appmag>
            <relmag>5</relmag>
        </extra>
    </SkyObservation>
<SkyObservation id="a-1415293733"><date>1415293733</date><coordinate ordType="EQ"><ords>10,100</ords></coordinate><name>dgsderg</name><notes>i hate the flu</notes><type>STAR</type><hops/><extra/></SkyObservation><SkyObservation id="a-1415295472"><date>1415295913</date><coordinate ordType="EQ"><ords>4.99,40</ords></coordinate><name>apple</name><notes>last addition before submission</notes><type>CLUSTER</type><hops/><extra/></SkyObservation></SkyObservations>

=== nebgor/Personal-digital-sky-survey/APP/SkyObs_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2014 aparup

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->


<SkyObservations
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='SkyObservations.xsd'>
    <SkyObservation id="1">
        <date>1412000535</date>
        <coordinate version="galactic">
            <ordsystem>26854.324,68546541.6564</ordsystem>
        </coordinate>
        <hops/>
        <type>STAR</type>
        <name>aafaf</name>
        <notes>let#quot;s try this</notes>
    </SkyObservation>
    <SkyObservation id="2">
        <date>1412000735</date>
        <coordinate version="galactic">
            <ordsystem>26854.324,68546541.6564</ordsystem>
        </coordinate>
        <hops>
            <id>1</id>
        </hops>    
        <type>STAR</type>
        <name>basfer</name>
        <notes>what#quot;s happening?</notes>
    </SkyObservation>
    <SkyObservation id="3">
        <date>1412000835</date>
        <coordinate version="galactic">
            <ordsystem>26854.324,68546541.6564</ordsystem>
        </coordinate>
        <hops>
            <id>1</id>
            <id>2</id>
        </hops>
        <type>STAR</type>
        <name>casdf</name>
        <notes>i dunno</notes>
    </SkyObservation>
</SkyObservations>
